### PR TITLE
Add Ubuntu version matrix

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 for you:

Failing on `xenial` (Ubuntu 16.04):

```
$ plantuml -testdot
The program 'plantuml' is currently not installed. To run 'plantuml' please ask your administrator to install the package 'plantuml'
The command "plantuml -testdot" exited with 127.
```

Failing both on `xenial` and `trusty` (14.04):

```
Building and testing Parse-RecDescent-1.967015 ... OK
Successfully installed Parse-RecDescent-1.967015
! Installing the dependencies failed: Module 'LWP' is not installed
! Bailing out the installation for LaTeXML-v0.8.2.
58 distributions installed
The command "sudo ./ubuntu.sh" exited with 1.
```

**Comment by CAMOBAP795** [comment]
@ronaldtse I have rebased this branch  (git rebase update-latexml) so please don't merge this before https://github.com/metanorma/metanorma-linux-setup/pull/6/files

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
