### PR TITLE
Feature/add latexml dependency

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- #3

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse @opoudjis ready for review

One open question will we (or not) move https://github.com/riboseinc/plantuml-install/ to "metanorma" org?

**Comment by ronaldtse** [comment]
> One open question will we (or not) move https://github.com/riboseinc/plantuml-install/ to "metanorma" org?

OK, we can move it over. @CAMOBAP795 can you help handle the dependencies?

**Comment by ronaldtse** [comment]
(moved)

**Comment by CAMOBAP795** [comment]
@ronaldtse done

**Pull request merged**
