### PR TITLE
Update LaTeXML to 0.8.3

### PR DESCRIPTION
**Pull request by ronaldtse**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@camobap795 could you help fix this? Thanks!

**Comment by CAMOBAP795** [comment]
@ronaldtse Sure, I will have check it today

**Comment by CAMOBAP795** [comment]
@ronaldtse problem with tests for ``

<details><summary>LWP module installation failure </summary>
<p>
```
cp lib/LWP.pm blib/lib/LWP.pm
cp lib/LWP/Protocol/cpan.pm blib/lib/LWP/Protocol/cpan.pm
cp lwptut.pod blib/lib/libwww/lwptut.pod
cp lib/LWP/RobotUA.pm blib/lib/LWP/RobotUA.pm
cp lib/LWP/Protocol/http.pm blib/lib/LWP/Protocol/http.pm
cp lib/LWP/Protocol/ftp.pm blib/lib/LWP/Protocol/ftp.pm
cp lib/LWP/Protocol/nntp.pm blib/lib/LWP/Protocol/nntp.pm
cp lib/LWP/DebugFile.pm blib/lib/LWP/DebugFile.pm
cp lib/LWP/Simple.pm blib/lib/LWP/Simple.pm
cp lib/LWP/ConnCache.pm blib/lib/LWP/ConnCache.pm
cp lib/LWP/Protocol/nogo.pm blib/lib/LWP/Protocol/nogo.pm
cp lib/LWP/Protocol/loopback.pm blib/lib/LWP/Protocol/loopback.pm
cp lib/LWP/Protocol/file.pm blib/lib/LWP/Protocol/file.pm
cp lib/LWP/Protocol/gopher.pm blib/lib/LWP/Protocol/gopher.pm
cp lib/LWP/MemberMixin.pm blib/lib/LWP/MemberMixin.pm
cp lib/LWP/Authen/Digest.pm blib/lib/LWP/Authen/Digest.pm
cp lib/LWP/UserAgent.pm blib/lib/LWP/UserAgent.pm
cp lib/LWP/Debug/TraceHTTP.pm blib/lib/LWP/Debug/TraceHTTP.pm
cp lib/LWP/Authen/Ntlm.pm blib/lib/LWP/Authen/Ntlm.pm
cp lib/LWP/Protocol/data.pm blib/lib/LWP/Protocol/data.pm
cp lib/LWP/Protocol.pm blib/lib/LWP/Protocol.pm
cp lwpcook.pod blib/lib/libwww/lwpcook.pod
cp lib/LWP/Authen/Basic.pm blib/lib/LWP/Authen/Basic.pm
cp lib/LWP/Debug.pm blib/lib/LWP/Debug.pm
cp lib/LWP/Protocol/mailto.pm blib/lib/LWP/Protocol/mailto.pm
cp bin/lwp-download blib/script/lwp-download
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lwp-download
cp bin/lwp-request blib/script/lwp-request
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lwp-request
cp bin/lwp-mirror blib/script/lwp-mirror
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lwp-mirror
cp bin/lwp-dump blib/script/lwp-dump
/usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/lwp-dump
Manifying blib/man1/lwp-request.1p
Manifying blib/man1/lwp-mirror.1p
Manifying blib/man1/lwp-dump.1p
Manifying blib/man1/lwp-download.1p
Manifying blib/man3/LWP::Authen::Ntlm.3pm
Manifying blib/man3/LWP::Simple.3pm
Manifying blib/man3/LWP::ConnCache.3pm
Manifying blib/man3/LWP::MemberMixin.3pm
Manifying blib/man3/libwww::lwpcook.3pm
Manifying blib/man3/LWP.3pm
Manifying blib/man3/LWP::Protocol.3pm
Manifying blib/man3/LWP::Debug.3pm
Manifying blib/man3/LWP::UserAgent.3pm
Manifying blib/man3/LWP::RobotUA.3pm
Manifying blib/man3/libwww::lwptut.3pm
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/base/*.t t/base/protocols/*.t t/leak/*.t t/local/*.t t/robot/*.t
# 
# Versions for all modules listed in MYMETA.json (including optional ones):
# 
# === Configure Requires ===
# 
#     Module                       Want     Have
#     ------------------------ -------- --------
#     CPAN::Meta::Requirements 2.120620    2.122
#     ExtUtils::MakeMaker           any     6.66
#     File::Copy                    any     2.26
#     Getopt::Long                  any     2.39
#     Module::Metadata              any 1.000011
# 
# === Build Requires ===
# 
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 6.66
# 
# === Test Requires ===
# 
#     Module                 Want     Have
#     ---------------------- ---- --------
#     ExtUtils::MakeMaker     any     6.66
#     File::Spec              any     3.40
#     FindBin                 any     1.51
#     Test::Fatal             any    0.014
#     Test::More              any 1.302164
#     Test::Needs             any 0.002006
#     Test::RequiresInternet  any     0.05
# 
# === Test Recommends ===
# 
#     Module              Want     Have
#     --------------- -------- --------
#     CPAN::Meta      2.120900 2.150010
#     Test::LeakTrace      any  missing
# 
# === Runtime Requires ===
# 
#     Module                Want Have
#     --------------------- ---- ----
#     Digest::MD5            any 2.52
#     Encode                2.12 2.49
#     Encode::Locale         any 1.05
#     File::Listing            6 6.04
#     HTML::Entities         any 3.69
#     HTML::HeadParser       any 3.71
#     HTTP::Cookies            6 6.04
#     HTTP::Daemon             6 6.04
#     HTTP::Date               6 6.02
#     HTTP::Negotiate          6 6.01
#     HTTP::Request            6 6.18
#     HTTP::Request::Common    6 6.18
#     HTTP::Response           6 6.18
#     HTTP::Status             6 6.18
#     IO::Select             any 1.21
#     IO::Socket             any 1.36
#     LWP::MediaTypes          6 6.04
#     MIME::Base64           2.1 3.13
#     Net::FTP              2.58 2.77
#     Net::HTTP             6.18 6.18
#     Scalar::Util           any 1.27
#     Try::Tiny              any 0.30
#     URI                   1.10 1.76
#     URI::Escape            any 3.31
#     WWW::RobotRules          6 6.02
#     base                   any 2.18
#     strict                 any 1.07
#     warnings               any 1.18
# 
# === Runtime Suggests ===
# 
#     Module               Want    Have
#     -------------------- ---- -------
#     Authen::NTLM         1.02 missing
#     Data::Dump           1.13 missing
#     IO::Socket::INET      any    1.33
#     LWP::Protocol::https 6.02 missing
# 
t/00-report-prereqs.t .......... ok
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
Use of uninitialized value in join or string at /home/travis/.cpanm/work/1557000556.18220/libwww-perl-6.38/blib/lib/LWP/UserAgent.pm line 676.
t/10-attrs.t ................... ok
# Some tests for the PUT method can only be run on 
# HTTP::Request version 6.07 or higher.
# If your version isn't good enough, we'll skip those.
# Your version is 6.18 and that's good enough
t/base/default_content_type.t .. ok
t/base/protocols.t ............. ok
#   Failed test '404 on fake nntp url'
#   at t/base/protocols/nntp.t line 12.
#          got: '500'
#     expected: '404'
# Looks like you failed 1 test of 1.
t/base/protocols/nntp.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/base/proxy.t ................. ok
t/base/simple.t ................ ok
Unrecognized LWP::UserAgent options: proxy at t/base/ua.t line 20.
t/base/ua.t .................... ok
t/base/ua_handlers.t ........... ok
t/leak/no_leak.t ............... skipped: Need Test::LeakTrace
t/local/autoload-get.t ......... ok
t/local/autoload.t ............. ok
t/local/get.t .................. ok
t/local/http.t ................. ok
t/local/httpsub.t .............. ok
t/local/protosub.t ............. ok
t/robot/ua-get.t ............... ok
t/robot/ua.t ................... ok
Test Summary Report
-------------------
t/base/protocols/nntp.t      (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=18, Tests=214, 15 wallclock secs ( 0.08 usr  0.02 sys +  2.41 cusr  0.28 csys =  2.79 CPU)
Result: FAIL
Failed 1/18 test programs. 1/214 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing LWP failed. See /home/travis/.cpanm/work/1557000556.18220/build.log for details. Retry with --force to force install it.
```
</p>
</details>

**Comment by ronaldtse** [comment]
The problem is it seems that 0.8.2 now shows the same error too?? Something wrong with LWP?

**Comment by CAMOBAP795** [comment]
@ronaldtse tests failed for it during installation, now I'm researching maybe there is some workaround for this l. If no, I propose roll back to 0.8.2, because for us no difference between these two versions

P.S. of course we can skip tests, but I didn't think that this is good approach

**Comment by CAMOBAP795** [comment]
this is known issue https://github.com/libwww-perl/libwww-perl/issues/307 I propose to rollback to 0.8.2

@ronaldtse  let me hear your opinion

**Comment by CAMOBAP795** [comment]
**_Update_** these tests failed for 8.2.0 too, looks like it does not depend on latexml version, looking for a way to disable tests for LWP

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review, sorry I cannot provide a better solution yet, lets wait for some updates from https://github.com/libwww-perl/libwww-perl/issues/307

**Comment by ronaldtse** [comment]
All tests pass, maybe the CPAN servers are up again...

**Pull request merged**
